### ISSUE TITLE
NLUEngine Config Multi-languages

### ISSUE THREAD

**Issue by lucasvercelot** [snipsco/snips-nlu#622]
Hi guys,

Is it possible/are you planning to allow a multi-languages dataset by loading several resources ?
I am working on a project which needs to handle both English and French, but actually I think it's not yet possible to train an engine or build a dataset with several Configs/Resources.

Thanks in advance !

**Comment by ClemDoum** [comment]
Hi Lucas,

For now it's possible to train a same engine on datasets that have different languages, you just need to load the resources beforehand. However each time you train an engine on a dataset, the engine will be trained for that dataset's language.

In our current setup we will always have one engine per language because the features we use to train the models (specifically the CRF) are highly language specific and yield better than non language specific features/models.

Depending on what you want to achieve you can do the following:
1. Separate your queries in different datasets
2. Train one engine per language
3. Use a language detection library like [langdetect](https://pypi.org/project/langdetect/) to detect the language
2. Use the language engine to perform inference

**Comment by lucasvercelot** [comment]
Thanks for your quick answer !

Actually, I'm building a chatbot that must answer in french or english depending on the user input.

Considering the poor quality of language detection libraries (Python, NodeJS, etc.) except the Google one, which is not free, I was thinking of using Snips' NLUEngine with both languages intents, for example : **HelloFR** and **HelloEN** intents.
That would have allowed me to have both the intent and the language in "one shot".

I don't know if I'm clear, but as far as I understand, I currently can't use this method.

**Comment by lucasvercelot** [comment]
Alright, thanks a lot for your help @ClemDoum ! 😄 
I'll see what I can do.
