### ISSUE TITLE
French stemmer does not stem correctly most of the time

### ISSUE THREAD

**Issue by mashao** [snipsco/snips-nlu#663]
I tried a french stemmer on some basic sentences, and found that many plurals do not get stemmed (chats,  lumières), and some words are stemmed quite unnecessarily (for example, changing the preposition “du” to the verb “devoir”). Below are some examples.
Can you please let me know if there is an existing better stemming algorithm available, and if there is a timeline for improving the current version?
I am working with the Genesys Dialog Engine - Snips integration.
Input:
puis-je peut-être réparer les dégâts et des problemes causés par les chats frivoles d’arrondisement qui sont allés et venus aujourd’hui et toujours, après avoir réveillé la bête du Paris. Et après, pouvez-vous éteindre les lumières dans la salle de bain des enfants. Les salles de bain, encore.
Output:
puis je pouvoir être réparer le dégâts et de problemes causés par le chats frivoles d arrondisement qui etre allés et venus aujourd huir et toujour après avoir réveillé la bête devoir Paris Et après pouvoir vous éteindre le lumières dan la sall de bain de enfant Les sall de bain encor

**Comment by ClemDoum** [comment]
Hi @mashao, we haven't really taken time to build a robust stemmer. We used [this lib](https://www.clips.uantwerpen.be/pattern) to get the stems of most frequent French words. We also took some shortcuts to make the stemming resources more compact.

Keep in mind that resources or stemming algorithm must fit on small devices since Snips NLU is part of the Snips Platform that is embedding in small devices. This means we can't afford to have heavy or slow stemmers. Our stemmers are far from perfect but we found it was a good trade-off between overall NLU performances and CPU/Memory footprint.
Another important point is that stemming is only used to extract some of the features for the models, if it's wrong the model can count on the other features to make it's decisions.

I wouldn't recommend using Snips NLU for the stemming  if you need a robust stemming i would recommend [Spacy](https://spacy.io/) or [pattern](https://www.clips.uantwerpen.be/pattern).

**Comment by mashao** [comment]
Thank you for your response!
