### ISSUE TITLE
[Intents] Handling malformed text input

### ISSUE THREAD

**Issue by lucasvercelot** [snipsco/snips-nlu#667]
Hi guys !

I would like some help with an issue that I have with some malformed text inputs.

I trained an engine with an intent named `hello` with some training sentences/words in it, among which is the word `bonjour`.

So, when I input the text 'bonjour', Snips NLU result shows 100% confidence :
`
{
input: 'bonjour',
slots: [],
intent: { intentName: 'hello', probability: 1 }
}
`

But when I input a tiny mistake like : 'bonjourr' with two letters `r`, it matches another intent that doesn't have the word 'bonjour' in it :
`
{
input: 'bonjourr',
slots: [],
intent: { intentName: 'rudewords', probability: 0.07246172118143608 }
}
`

Or, another example, with the letter `r` at the beginning of the word :
`
{
input: 'rbonjour',
slots: [],
intent: { intentName: 'rudewords', probability: 0.07246172118143608 }
}
`

I would love to have some help/insights here.

Thanks in advance !

**Comment by adrienball** [comment]
Hi @lucasvercelot ,
At the moment, the intent classification does not handle typos. The model is a logistic regression which operates at the word level (and not at the character level), hence words are matched as they are, or with a simple stemming. 
As a simple workaround, if there are typical typos that you have in mind, you can add them to the training data.
Otherwise, you can use a spell checker to clean your inputs before they are parsed by Snips NLU.

Adrien

**Comment by lucasvercelot** [comment]
@adrienball Ok, thank you.
Is this feature on your roadmap or not ?

**Comment by adrienball** [comment]
@lucasvercelot From our point of view, this feature is a bit out of scope and it should be treated as an independent preprocessing step. So we are not planning to work on this for now.

**Comment by lucasvercelot** [comment]
Alright, thank you for your help @adrienball ! 🙂
