### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by flozi00** [snipsco/snips-nlu#877]
Since snips was taken over by Sonos, the question arises how to proceed with this repository. Does it make sense to switch your software to other engines like Rasa?
Is it possible to integrate the language resources into this repository? some of the built-in entities are downloaded from snips servers.

It's still a great library and I hope you still keep it alive

**Comment by adrienball** [comment]
Hi @flozi00 ,
One of the consequences of the acquisition of Snips by Sonos is that our focus has shifted a bit and we are no longer actively working on and developing this repository.
That being said, and because we believe this library can still be useful as is for many people, we will continue to provide bug fixes when users report them, and accept contributions.

We understand that developers need some visibility in order to know in what to invest and when to switch. 
I would say that if you are relying on snips-nlu for NLU tasks that are not necessarily core in what you do and are not meant to evolve a lot, it is probably still a good fit.
If NLU is a core thing in what you build, we would recommend switching to an actively maintained library such as RASA indeed.

Regarding the resources: the language resources are already stored as [github releases](https://github.com/snipsco/snips-nlu-language-resources/releases). 
However, some builtin entity resources are stored in one of our S3 buckets. This is the case for the six builtin music entities:
- `snips/musicAlbum`
- `snips/musicArtist`
- `snips/musicTrack`
- `snips/city`
- `snips/country`
- `snips/region`

We will move these entities to github as well to make sure everything stays available.
Thanks
